In [6]:
import numpy as np


In [7]:
a=[2,4,6,8,10]


In [8]:
b=np.array(a)

In [9]:
b

array([ 2,  4,  6,  8, 10])

In [11]:
b.cumsum()  # Last Element may Next elemt ko plus karay ga Karay ga

array([ 2,  6, 12, 20, 30], dtype=int32)

In [14]:
b.cumprod()   #Yani asal Aray k elemnts ko multiply karay ga result say 2 aysay hi aa jay ga phir next elemt hay 4 wo multiply
              # hoga previous say yani 4*2, phir jo result aay ga wo print hoga phir next elemt is result say multiply hoga
              # yani 6* jo result aay tha 4*2 ka us say wo print karay ga phir is result say next element yani 8 * hoga aur 
              # print kar day ga

array([   2,    8,   48,  384, 3840], dtype=int32)

In [15]:
b

array([ 2,  4,  6,  8, 10])

In [36]:
a=[[2,3,4,5],[6,7,8,9]]
b=[[12,13,14,15],[16,17,18,19]]


In [44]:
f1=np.array(a)
f2=np.array(b)

In [45]:
f1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [46]:
f2

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
c=np.concatenate((f1,f2),axis=0)   # Concatenate ka matlab hay milana aur Axis=0 ka matlab hay Row wise
c

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [48]:
d=np.concatenate((f1,f2),axis=1)  # Concatenate ka matlab hay milana aur Axis=1 ka matlab hay Colomn wise
d

array([[ 2,  3,  4,  5, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 16, 17, 18, 19]])

In [49]:
f1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [50]:
f2

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [52]:
e=np.vstack((f1,f2))  # is may bhi milata hay aur is tareqay say axis ki method nhi dayna Vstack ka matlab hi yay hay k Row wise
e

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [54]:
f=np.hstack((f1,f2)) #is may bhi milata hay aur is tareqay say axis ki method nhi dayna Hstack ka matlab hi yay hay k Colmn wise
f

array([[ 2,  3,  4,  5, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 16, 17, 18, 19]])

In [58]:
f1.ndim

2

In [59]:
f.shape

(2, 8)

In [62]:
k=f.reshape(2,2,2,2)

In [63]:
k

array([[[[ 2,  3],
         [ 4,  5]],

        [[12, 13],
         [14, 15]]],


       [[[ 6,  7],
         [ 8,  9]],

        [[16, 17],
         [18, 19]]]])

In [64]:
f

array([[ 2,  3,  4,  5, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 16, 17, 18, 19]])

In [66]:
f[0:,0:1]

array([[2],
       [6]])

In [70]:
k=f.reshape(2,2,4)
k

array([[[ 2,  3,  4,  5],
        [12, 13, 14, 15]],

       [[ 6,  7,  8,  9],
        [16, 17, 18, 19]]])

In [72]:
k[0:-1,1:3,0:2]

array([[[12, 13]]])

In [73]:
k[:,1:3,0:2]

array([[[12, 13]],

       [[16, 17]]])