In [1]:
import numpy as np

In [16]:
x=np.array([1,6,9,2,10,7])   #Aik Array Create kia


In [17]:
x

array([ 1,  6,  9,  2, 10,  7])

In [18]:
x[1:3]   # Slicing ki bilkul list ki tarah

array([6, 9])

In [19]:
y=np.sort(x)    #Sort kia bilkul list ki tarah yani ascending order may

In [20]:
y

array([ 1,  2,  6,  7,  9, 10])

In [21]:
a=np.zeros((5,6))    # Array Banaya Zeros ka , 0 aur 1 ka array is tarah ban sakta hay baqi nahi baqi ko multiply kar ka
a                    # bana saktay hain

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
a[1:-1,1:-1]=1     # pora border 1 kardia slicing ki madad say pahlay [ , ] Row kay liya aur dosra colomn k liya
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
x=np.array([1,5,6,2,1,6,7,5,10])   # Is may Repeat khatam kar kay unique item ko sort ka ky day day ga
y=np.unique(x)
y

array([ 1,  2,  5,  6,  7, 10])

In [27]:
x=np.ones((5,7))    # one element say 5 by 7 ka array banaya
x 

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [28]:
x=np.ones((5,7))*4   # one element say 5 by 7 ka array banaya ab jo banana hay us say multiply kar dain
x 

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [29]:
x=np.array([1,3,8,9,10,15,6,10,6,16,20])
x

array([ 1,  3,  8,  9, 10, 15,  6, 10,  6, 16, 20])

In [30]:
x[1:3]  # Slicing may elemnt 0 say shuru hotay hain so 0 1 2 ki value show kar day ga ,slicing may last say pahlay tak hota hay

array([3, 8])

In [31]:
x[:]    # start say end tak kiun k donu taraf yani : kay donu taraf blank means star say end

array([ 1,  3,  8,  9, 10, 15,  6, 10,  6, 16, 20])

In [32]:
x[3:]   # is may element # 3 say end tak

array([ 9, 10, 15,  6, 10,  6, 16, 20])

In [33]:
x[:4]    # is may start say Element # 4 say pahlay tak yani Element # 3 tak

array([1, 3, 8, 9])

In [37]:
x=np.ones((5,7))*4   
x 

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [39]:
x[2:]=5
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.]])

In [48]:
x=np.ones((5,7))*4   
x 

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [49]:
x[:4]=5
x

array([[5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [60]:
x=np.ones((5,7))*4   
x 

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [61]:
x[1:-1]=5
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [72]:
x=np.ones((5,7))*4   
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [73]:
x[1:-1,1:-1]=2
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 2., 2., 2., 2., 2., 4.],
       [4., 2., 2., 2., 2., 2., 4.],
       [4., 2., 2., 2., 2., 2., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [74]:
x=np.ones((5,7))*4   
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [75]:
x[1:-1,1:-2]=2
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 2., 2., 2., 2., 4., 4.],
       [4., 2., 2., 2., 2., 4., 4.],
       [4., 2., 2., 2., 2., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [76]:
x=np.ones((5,7))*4   
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [77]:
x[1:-1,1:5]=2
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 2., 2., 2., 2., 4., 4.],
       [4., 2., 2., 2., 2., 4., 4.],
       [4., 2., 2., 2., 2., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [78]:
x=np.ones((5,7))*4   
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [79]:
x[1:-1,1:4]=2
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 2., 2., 2., 4., 4., 4.],
       [4., 2., 2., 2., 4., 4., 4.],
       [4., 2., 2., 2., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [84]:
x=np.ones((5,7))*4
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [85]:
x[0,1:-1]=6   # yani Row 0 may colomn 1 say -1 ya 6 tak 6 print kar do
x

array([[4., 6., 6., 6., 6., 6., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [86]:
x=np.array((2,5,6,8,9,11,3,5,)) # List may hum aik sath pori list ko * , / , + , - nahi kar saktay Loop lagana hoga magar
                                # numpy may easily ho sakta hay

In [91]:
x=np.ones((5,7))*4
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [92]:
x[1:3,1:5]=1
x

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 1., 1., 1., 1., 4., 4.],
       [4., 1., 1., 1., 1., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [87]:
x*5

array([10, 25, 30, 40, 45, 55, 15, 25])

In [88]:
x+2

array([ 4,  7,  8, 10, 11, 13,  5,  7])

In [89]:
x/6

array([0.33333333, 0.83333333, 1.        , 1.33333333, 1.5       ,
       1.83333333, 0.5       , 0.83333333])

In [90]:
x**2

array([  4,  25,  36,  64,  81, 121,   9,  25], dtype=int32)

In [2]:
name=np.array(["Naveed","Samad","Kashif","Irfan","Javaid"])
print(name)

['Naveed' 'Samad' 'Kashif' 'Irfan' 'Javaid']


In [3]:
marks=np.array([72,65,35,81,92])
print(marks)

[72 65 35 81 92]


In [4]:
name[marks>70]  # name aur marks ko compare kar ka bataiy ga k kis name kay against marks 70 say above hain

array(['Naveed', 'Irfan', 'Javaid'], dtype='<U6')

In [5]:
name[marks<70]  # kis name kay against marks 70 say kam hain

array(['Samad', 'Kashif'], dtype='<U6')

In [6]:
marks>60   # jo marks 60 say above hain un ka bullien reply day ga

array([ True,  True, False,  True,  True])

In [7]:
marks[marks>60]  # jo marks 60 say above hain un ko show kar day ga

array([72, 65, 81, 92])