In [1]:
import numpy as np

In [5]:
x = np.zeros((2,6))
print(x)# An array of zeros with 2 rows and 6 columns

print("\nShape of array: ")

print(x.shape)
print("\nReshape: 1 row 12 columns")
y = x.reshape(1, 12)
print(y)


print("\nReshape: 6 row 2 columns")
y = x.reshape(6, 2)
print(y)


print("\nReshape: A 3D Array of 2 plains , 3 rows and 2 columns")
y = x.reshape(2,3,2)
print(y)


print("\nReshape: 3 Plains 2 rows 2 columns")
y = x.reshape(3,2,2)
print(y)


print("\nReshape: 2 Plains 2 rows 3 columns")
y = x.reshape(2,2,3)
print(y)


print("\nReshape: 4 Plains 1 rows 3 columns")
y = x.reshape(4,1,3)
print(y)

print("\nReshape: 6 Plains 1 rows 2 columns")
y = x.reshape(6,1,2)
print(y)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Shape of array: 
(2, 6)

Reshape: 1 row 12 columns
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Reshape: 6 row 2 columns
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Reshape: A 3D Array of 2 plains , 3 rows and 2 columns
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]

Reshape: 3 Plains 2 rows 2 columns
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

Reshape: 2 Plains 2 rows 3 columns
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

Reshape: 4 Plains 1 rows 3 columns
[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]

Reshape: 6 Plains 1 rows 2 columns
[[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]]


In [8]:
x = np.zeros((2,6))
print(x)

y = x.reshape(1, -12) #It ignores the Negative sign and print matrix 1 row 1 columns
print(y)

y = x.reshape(3,2,-2) #It ignores the Negative sign and print matrix 3 plains 2 row 2 columns
print(y)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [10]:
l=range(1000000)
l

range(0, 1000000)

In [28]:
%time for i in l:i*7

Wall time: 269 ms


In [29]:
import numpy as np

In [30]:
l=np.arange(1000000)

In [31]:
%time l*7

Wall time: 18.6 ms


array([      0,       7,      14, ..., 6999979, 6999986, 6999993])

In [ ]:
l1=range(1000000)
l2=range(1000000)

In [ ]:
%time for i in range(1000000): l1[i]+l2[i]

In [ ]:
a1=np.arange(1000000)
a2=np.arange(1000000)

In [ ]:
%time a1+a2

In [2]:
l1=[1,4,5,7,9]
l2=[11,14,15,17,19]

In [3]:
for i in range(5): print(l1[i]+l2[i])

12
18
20
24
28


In [4]:
np.zeros((8,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,7))

In [5]:
np.array([[1,3,4],[3,7,8]])

array([[1, 3, 4],
       [3, 7, 8]])

In [6]:
x=np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]])

In [7]:
x

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [8]:
x[2]

array([ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ])

In [ ]:
x

In [ ]:
x[:,2]

In [ ]:
x

In [ ]:
x[:,5]

In [11]:
x=np.array([[[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]],
            [[12, 13.2, 5.51, -6.41, -21.2, 2.41], [11, 212, 14, 0.11, 51.3, -91], [31, 11, 21, 2.1, 1.21, -12]]])

In [12]:
x

array([[[ 2.00e+00,  3.20e+00,  5.50e+00, -6.40e+00, -2.20e+00,
          2.40e+00],
        [ 1.00e+00,  2.20e+01,  4.00e+00,  1.00e-01,  5.30e+00,
         -9.00e+00],
        [ 3.00e+00,  1.00e+00,  2.10e+00,  2.10e+01,  1.10e+00,
         -2.00e+00]],

       [[ 1.20e+01,  1.32e+01,  5.51e+00, -6.41e+00, -2.12e+01,
          2.41e+00],
        [ 1.10e+01,  2.12e+02,  1.40e+01,  1.10e-01,  5.13e+01,
         -9.10e+01],
        [ 3.10e+01,  1.10e+01,  2.10e+01,  2.10e+00,  1.21e+00,
         -1.20e+01]]])

In [ ]:
x[0]

In [ ]:
x[1]

In [ ]:
x[0,1]

In [ ]:
x[0,:,1]

In [ ]:
x

In [ ]:
x[1,:,0]

In [13]:
[range(4), range(10, 14)]

[range(0, 4), range(10, 14)]

In [14]:
x=np.array([range(4), range(10, 14)] )

In [15]:
x

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
b = np.arange(1,9)
b

In [ ]:
a = b.reshape(2,4)
a

In [ ]:
c = np.array([1,2])
c

In [ ]:
d = c.reshape(2,1)
d

In [ ]:
b + d

In [ ]:
a + c

In [ ]:
a=[7,9,-9,8,3]

In [ ]:
b=np.array(a)

In [ ]:
b[b%2==0]

In [ ]:
b[[4,1,3]]

In [ ]:
np.square(b)

In [17]:
salary = np.array([-1,100000,200000,300000])

In [18]:
np.where(salary<0,10000,salary)

array([ 10000, 100000, 200000, 300000])

In [19]:
np.where(salary<0,np.mean(salary),salary)

array([149999.75, 100000.  , 200000.  , 300000.  ])

In [20]:
salary.T

array([    -1, 100000, 200000, 300000])

In [23]:
np.transpose(salary)

array([    -1, 100000, 200000, 300000])

In [24]:
salary

array([    -1, 100000, 200000, 300000])

In [25]:
np.cumsum(salary)

array([    -1,  99999, 299999, 599999], dtype=int32)

In [26]:
np.cumprod(salary)


array([        -1,    -100000, 1474836480,  593035264], dtype=int32)