In [2]:
import numpy as np

In [2]:
x=np.zeros((2,6))

In [3]:
x

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
x.shape

(2, 6)

In [5]:
x = np.zeros((2,6))
print(x)# An array of zeros with 2 rows and 6 columns

print("Shape of array: ")

print(x.shape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Shape of array: 
(2, 6)


In [6]:
print("Reshape: 1 row 12 columns")
y = x.reshape(1, 12)
print(y)


Reshape: 1 row 12 columns
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
print("Reshape: 6 row 2 columns")
y = x.reshape(6, 2)
print(y)

Reshape: 6 row 2 columns
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
print("Reshape: A 3D Array of 2 plains , 3 rows and 2 columns")
y = x.reshape(2,3,2)
print(y)


Reshape: A 3D Array of 2 plains , 3 rows and 2 columns
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [9]:
print("Reshape: 3 Plains 2 rows 2 columns")
y = x.reshape(3,2,2)
print(y)

Reshape: 3 Plains 2 rows 2 columns
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [10]:
print("Reshape: 2 Plains 2 rows 3 columns")
y = x.reshape(2,2,3)
print(y)

Reshape: 2 Plains 2 rows 3 columns
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [11]:
print("Reshape: 4 Plains 1 rows 3 columns")
y = x.reshape(4,1,3)
print(y)

Reshape: 4 Plains 1 rows 3 columns
[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]


In [12]:
print("Reshape: 6 Plains 1 rows 2 columns")
y = x.reshape(6,1,2)
print(y)

Reshape: 6 Plains 1 rows 2 columns
[[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]]


In [7]:
np.ones_like((9,6))*2

array([2, 2])

In [11]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [16]:
a=[2,3,4,5]
b=[6,7,8,9]
f1=np.array(a)
f2=np.array(b)

In [17]:
f1

array([2, 3, 4, 5])

In [18]:
f2

array([6, 7, 8, 9])

In [20]:
d=f1*f2  # Jab 2 Array ko Multiply karain gay to apas may Multiply karay ga yani 1 array ka 1 element 2 array k 1 element say
d        # aur isi Tarah first array k 2nd element ko 2nd array k 2nd Array Say Multiply kar day ga

array([12, 21, 32, 45])

In [21]:
f3=np.array([[1,2,3,4],[5,6,7,8]])
f3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
f3*f3   # agar aik array 2 Dimension ka hay to is tareqay say har element ka Square aa jay ga yani 1*1,4*4,9*9,16*16

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [23]:
f3**2   # Yay Dakahin Donu ka Result Same hay

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [24]:
f3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])